In [1]:
import pandas as pd
import numpy as np

In [2]:
data = "https://raw.githubusercontent.com/gastonstat/CreditScoring/master/CreditScoring.csv"

In [4]:
!wget $data

--2026-02-20 01:42:36--  https://raw.githubusercontent.com/gastonstat/CreditScoring/master/CreditScoring.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182489 (178K) [text/plain]
Saving to: ‘CreditScoring.csv.1’

CreditScoring.csv.1 100%[===================>] 178.21K  --.-KB/s    in 0.1s

2026-02-20 01:42:37 (1.52 MB/s) - ‘CreditScoring.csv.1’ saved [182489/182489]

In [3]:
df = pd.read_csv(data)

In [4]:
df.head()

,Status,Seniority,Home,Time,Age,Marital,Records,Job,Expenses,Income,Assets,Debt,Amount,Price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [5]:
df.columns = df.columns.str.lower()

In [6]:
df.status.value_counts()

status
1    3200
2    1254
0       1
Name: count, dtype: int64

In [7]:
status_values = {
    1:'ok',
    2:'default',
    0:'unk'
}
df.status = df.status.map(status_values)

home_values = {
    1: 'rent',
    2: 'owner',
    3: 'private',
    4: 'ignore',
    5: 'parents',
    6: 'other',
    0: 'unk'
}
df.home = df.home.map(home_values)
 
marital_values = {
    1: 'single', 
    2: 'married', 
    3: 'widow', 
    4: 'separated',
    5: 'divorced',
    0: 'unk'
}
df.marital = df.marital.map(marital_values)
 
records_values = {
    1: 'no',
    2: 'yes',
    0: 'unk'
}
df.records = df.records.map(records_values)
 
job_values = {
    1: 'fixed', 
    2: 'partime', 
    3: 'freelance', 
    4: 'others',
    0: 'unk'
}
df.job = df.job.map(job_values)
 
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107,0,0,310,910

In [8]:
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,763317.0,1060341.0,404382.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,8703625.0,10217569.0,6344253.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3500.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,166.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,99999999.0,99999999.0,99999999.0,5000.0,11140.0

In [9]:
for c in ['income', 'assets', 'debt']:
    df[c] = df[c].replace(to_replace=99999999, value=np.nan)

In [10]:
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4421.0,4408.0,4437.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,131.0,5403.0,343.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,86.0,11573.0,1246.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3000.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,165.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,959.0,300000.0,30000.0,5000.0,11140.0

In [11]:
df[df.status != 'unk'].reset_index(drop = True)

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129.0,0.0,0.0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131.0,0.0,0.0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200.0,3000.0,0.0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182.0,2500.0,0.0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107.0,0.0,0.0,310,910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4449,default,1,rent,60,39,married,no,fixed,69,92.0,0.0,0.0,900,1020
4450,ok,22,owner,60,46,married,no,fixed,60,75.0,3000.0,600.0,950,1263
4451,default,0,owner,24,37,married,no,partime,60,90.0,3500.0,0.0,500,963
4452,ok,0,rent,48,23,single,no,freelance,49,140.0,0.0,0.0,550,550
4453,ok,5,owner,60,32,married,no,freelance,60,140.0,4000.0,1000.0,1350,1650

In [12]:
df = df[df.status != 'unk'].reset_index(drop = True)

In [13]:
df

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129.0,0.0,0.0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131.0,0.0,0.0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200.0,3000.0,0.0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182.0,2500.0,0.0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107.0,0.0,0.0,310,910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4449,default,1,rent,60,39,married,no,fixed,69,92.0,0.0,0.0,900,1020
4450,ok,22,owner,60,46,married,no,fixed,60,75.0,3000.0,600.0,950,1263
4451,default,0,owner,24,37,married,no,partime,60,90.0,3500.0,0.0,500,963
4452,ok,0,rent,48,23,single,no,freelance,49,140.0,0.0,0.0,550,550
4453,ok,5,owner,60,32,married,no,freelance,60,140.0,4000.0,1000.0,1350,1650

### Uptill now we did data cleaning 
    ->column names lowercase kiya
    ->Based on R files (which I dont have), we will see that categoriacal columns have numerical values, they should be given their correct values to make them more meaningful
    ->So we replace values like 0,1,2,3,4 with correct names. 0 is unknown
    ->We check numerical columns now. 9999999 is used for unknown values, we replace it with NaN.
    ->We had one unkown values in our target column, we should remove that data point itself to keep the target column binary (1,2). We dont do so for other unknown values.

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
df_full_train, df_test = train_test_split(df, test_size = 0.2, random_state = 11)

In [16]:
df_train, df_val = train_test_split(df_full_train, test_size = 0.25, random_state = 11)

In [17]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [18]:
y_train = (df_train.status == 'default').astype('int').values

In [19]:
y_train = (df_train.status == 'default').astype('int').values
y_val = (df_val.status == 'default').astype('int').values
y_test = (df_test.status == 'default').astype('int').values

In [20]:
y_train

array([1, 1, 0, ..., 0, 0, 0], shape=(2672,))

In [21]:
del df_train['status']
del df_val['status']
del df_test['status']

In [22]:
df_train

,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,10,owner,36,36,married,no,freelance,75,0.0,10000.0,0.0,1000,1400
1,6,parents,48,32,single,yes,fixed,35,85.0,0.0,0.0,1100,1330
2,1,parents,48,40,married,no,fixed,75,121.0,0.0,0.0,1320,1600
3,1,parents,48,23,single,no,partime,35,72.0,0.0,0.0,1078,1079
4,5,owner,36,46,married,no,freelance,60,100.0,4000.0,0.0,1100,1897
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667,18,private,36,45,married,no,fixed,45,220.0,20000.0,0.0,800,1600
2668,7,private,60,29,married,no,fixed,60,51.0,3500.0,500.0,1000,1290
2669,1,parents,24,19,single,no,fixed,35,28.0,0.0,0.0,400,600
2670,15,owner,48,43,married,no,freelance,60,100.0,18000.0,0.0,2500,2976
2671,12,owner,48,27,married,yes,fixed,45,110.0,5000.0,1300.0,450,1636

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [24]:
from sklearn.feature_extraction import DictVectorizer

In [25]:
from sklearn.metrics import roc_auc_score

In [26]:
df_train = df_train.fillna(0)

In [27]:
df_train.to_dict(orient = "records")

[{'seniority': 10,
  'home': 'owner',
  'time': 36,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 75,
  'income': 0.0,
  'assets': 10000.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 1400},
 {'seniority': 6,
  'home': 'parents',
  'time': 48,
  'age': 32,
  'marital': 'single',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 35,
  'income': 85.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1100,
  'price': 1330},
 {'seniority': 1,
  'home': 'parents',
  'time': 48,
  'age': 40,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 121.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1320,
  'price': 1600},
 {'seniority': 1,
  'home': 'parents',
  'time': 48,
  'age': 23,
  'marital': 'single',
  'records': 'no',
  'job': 'partime',
  'expenses': 35,
  'income': 72.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1078,
  'price': 1079},
 {'seniority': 5,
  'home': 'owner',
  'time': 36,
  'age': 46,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 60,
  'income': 100.0,
  'assets': 4000.0,
  'debt': 0.0,
  'amount': 1100,
  'price': 1897},
 {'seniority': 0,
  'home': 'parents',
  'time': 48,
  'age': 28,
  'marital': 'divorced',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 35,
  'income': 280.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1300,
  'price': 2058},
 {'seniority': 3,
  'home': 'parents',
  'time': 60,
  'age': 24,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 100.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1500,
  'price': 2100},
 {'seniority': 1,
  'home': 'rent',
  'time': 60,
  'age': 33,
  'marital': 'married',
  'records': 'no',
  'job': 'partime',
  'expenses': 85,
  'income': 250.0,
  'assets': 5000.0,
  'debt': 0.0,
  'amount': 1700,
  'price': 1878},
 {'seniority': 0,
  'home': 'owner',
  'time': 60,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'partime',
  'expenses': 90,
  'income': 113.0,
  'assets': 4000.0,
  'debt': 198.0,
  'amount': 400,
  'price': 790},
 {'seniority': 1,
  'home': 'owner',
  'time': 24,
  'age': 32,
  'marital': 'married',
  'records': 'no',
  'job': 'partime',
  'expenses': 45,
  'income': 182.0,
  'assets': 4000.0,
  'debt': 200.0,
  'amount': 175,
  'price': 175},
 {'seniority': 1,
  'home': 'owner',
  'time': 48,
  'age': 39,
  'marital': 'married',
  'records': 'yes',
  'job': 'freelance',
  'expenses': 60,
  'income': 0.0,
  'assets': 6000.0,
  'debt': 0.0,
  'amount': 1300,
  'price': 3626},
 {'seniority': 15,
  'home': 'rent',
  'time': 48,
  'age': 40,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 57,
  'income': 120.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 1500},
 {'seniority': 6,
  'home': 'owner',
  'time': 60,
  'age': 29,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 125.0,
  'assets': 5000.0,
  'debt': 0.0,
  'amount': 1500,
  'price': 1531},
 {'seniority': 2,
  'home': 'owner',
  'time': 36,
  'age': 27,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 156.0,
  'assets': 6000.0,
  'debt': 0.0,
  'amount': 700,
  'price': 1045},
 {'seniority': 1,
  'home': 'parents',
  'time': 48,
  'age': 23,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 65.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 400,
  'price': 1195},
 {'seniority': 3,
  'home': 'private',
  'time': 60,
  'age': 27,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 194.0,
  'assets': 3500.0,
  'debt': 1000.0,
  'amount': 700,
  'price': 1083},
 {'seniority': 16,
  'home': 'parents',
  'time': 48,
  'age': 35,
  'marital': 'separated',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 103.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 500,
  'price': 862},
 {'seniority': 22,
  'home': 'owner',
  'time': 48,
  'age': 40,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 180.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1200,
  'price': 2206},
 {'seniority': 6,
  'home': 'parents',
  'time': 60,
  'age': 38,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 75.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1175,
  'price': 1800},
 {'seniority': 16,
  'home': 'parents',
  'time': 60,
  'age': 31,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 160.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1400,
  'price': 1850},
 {'seniority': 2,
  'home': 'rent',
  'time': 36,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 95,
  'income': 200.0,
  'assets': 5000.0,
  'debt': 0.0,
  'amount': 800,
  'price': 1158},
 {'seniority': 2,
  'home': 'owner',
  'time': 60,
  'age': 38,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 88.0,
  'assets': 3500.0,
  'debt': 500.0,
  'amount': 1100,
  'price': 1263},
 {'seniority': 2,
  'home': 'parents',
  'time': 60,
  'age': 25,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 110.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 860,
  'price': 959},
 {'seniority': 18,
  'home': 'owner',
  'time': 48,
  'age': 32,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 71.0,
  'assets': 4000.0,
  'debt': 39.0,
  'amount': 660,
  'price': 1461},
 {'seniority': 10,
  'home': 'rent',
  'time': 36,
  'age': 45,
  'marital': 'married',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 83,
  'income': 383.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 800,
  'price': 4300},
 {'seniority': 0,
  'home': 'owner',
  'time': 24,
  'age': 30,
  'marital': 'married',
  'records': 'no',
  'job': 'partime',
  'expenses': 60,
  'income': 76.0,
  'assets': 4500.0,
  'debt': 0.0,
  'amount': 400,
  'price': 450},
 {'seniority': 18,
  'home': 'rent',
  'time': 48,
  'age': 53,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 54,
  'income': 92.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1340,
  'price': 1345},
 {'seniority': 10,
  'home': 'rent',
  'time': 60,
  'age': 42,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 76,
  'income': 158.0,
  'assets': 5000.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 1000},
 {'seniority': 5,
  'home': 'rent',
  'time': 48,
  'age': 31,
  'marital': 'single',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 47,
  'income': 120.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 900,
  'price': 1492},
 {'seniority': 2,
  'home': 'owner',
  'time': 36,
  'age': 37,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 125.0,
  'assets': 2000.0,
  'debt': 0.0,
  'amount': 450,
  'price': 1490},
 {'seniority': 23,
  'home': 'rent',
  'time': 48,
  'age': 57,
  'marital': 'single',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 49,
  'income': 142.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1300,
  'price': 1450},
 {'seniority': 15,
  'home': 'owner',
  'time': 48,
  'age': 53,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 75,
  'income': 100.0,
  'assets': 17000.0,
  'debt': 0.0,
  'amount': 500,
  'price': 1114},
 {'seniority': 1,
  'home': 'other',
  'time': 36,
  'age': 37,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 60,
  'income': 27.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 850,
  'price': 1000},
 {'seniority': 19,
  'home': 'owner',
  'time': 60,
  'age': 49,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 135,
  'income': 150.0,
  'assets': 3500.0,
  'debt': 0.0,
  'amount': 1100,
  'price': 1477},
 {'seniority': 23,
  'home': 'other',
  'time': 60,
  'age': 43,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 155.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1650,
  'price': 2270},
 {'seniority': 2,
  'home': 'owner',
  'time': 36,
  'age': 30,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 350.0,
  'assets': 4000.0,
  'debt': 0.0,
  'amount': 800,
  'price': 1800},
 {'seniority': 2,
  'home': 'rent',
  'time': 60,
  'age': 42,
  'marital': 'single',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 35,
  'income': 0.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1900,
  'price': 2259},
 {'seniority': 1,
  'home': 'rent',
  'time': 48,
  'age': 37,
  'marital': 'separated',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 46,
  'income': 110.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 900,
  'price': 1312},
 {'seniority': 3,
  'home': 'owner',
  'time': 60,
  'age': 38,
  'marital': 'married',
  'records': 'no',
  'job': 'partime',
  'expenses': 75,
  'income': 90.0,
  'assets': 3000.0,
  'debt': 0.0,
  'amount': 930,
  'price': 1135},
 {'seniority': 15,
  'home': 'owner',
  'time': 24,
  'age': 29,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 130.0,
  'assets': 4000.0,
  'debt': 0.0,
  'amount': 400,
  'price': 899},
 {'seniority': 24,
  'home': 'other',
  'time': 60,
  'age': 41,
  'marital': 'married',
  'records': 'yes',
  'job': 'freelance',
  'expenses': 75,
  'income': 0.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 2200,
  'price': 2428},
 {'seniority': 6,
  'home': 'parents',
  'time': 60,
  'age': 29,
  'marital': 'single',
  'records': 'no',
  'job': 'freelance',
  'expenses': 35,
  'income': 0.0,
  'assets': 3500.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 1183},
 {'seniority': 1,
  'home': 'parents',
  'time': 48,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'partime',
  'expenses': 60,
  'income': 150.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 1148},
 {'seniority': 13,
  'home': 'private',
  'time': 24,
  'age': 59,
  'marital': 'widow',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 87.0,
  'assets': 1200.0,
  'debt': 0.0,
  'amount': 425,
  'price': 750},
 {'seniority': 6,
  'home': 'other',
  'time': 48,
  'age': 25,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 300.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 2400,
  'price': 2700},
 {'seniority': 16,
  'home': 'private',
  'time': 48,
  'age': 34,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 85.0,
  'assets': 2000.0,
  'debt': 0.0,
  'amount': 800,
  'price': 1866},
 {'seniority': 6,
  'home': 'parents',
  'time': 12,
  'age': 23,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 100.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 475,
  'price': 1080},
 {'seniority': 6,
  'home': 'rent',
  'time': 60,
  'age': 41,
  'marital': 'divorced',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 55,
  'income': 97.0,
  'assets': 7000.0,
  'debt': 5000.0,
  'amount': 1900,
  'price': 2260},
 {'seniority': 3,
  'home': 'owner',
  'time': 36,
  'age': 28,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 35,
  'income': 180.0,
  'assets': 5000.0,
  'debt': 0.0,
  'amount': 375,
  'price': 1139},
 {'seniority': 6,
  'home': 'owner',
  'time': 36,
  'age': 49,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 60,
  'income': 100.0,
  'assets': 22000.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 1790},
 {'seniority': 9,
  'home': 'owner',
  'time': 60,
  'age': 24,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 125.0,
  'assets': 4000.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 1174},
 {'seniority': 1,
  'home': 'private',
  'time': 48,
  'age': 36,
  'marital': 'single',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 35,
  'income': 173.0,
  'assets': 7700.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 2008},
 {'seniority': 20,
  'home': 'owner',
  'time': 60,
  'age': 47,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 90,
  'income': 212.0,
  'assets': 11000.0,
  'debt': 0.0,
  'amount': 1150,
  'price': 1669},
 {'seniority': 14,
  'home': 'owner',
  'time': 48,
  'age': 53,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 95.0,
  'assets': 3000.0,
  'debt': 0.0,
  'amount': 1060,
  'price': 1060},
 {'seniority': 3,
  'home': 'owner',
  'time': 36,
  'age': 37,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 55.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1500,
  'price': 2315},
 {'seniority': 0,
  'home': 'owner',
  'time': 60,
  'age': 61,
  'marital': 'married',
  'records': 'no',
  'job': 'others',
  'expenses': 35,
  'income': 113.0,
  'assets': 3000.0,
  'debt': 0.0,
  'amount': 1300,
  'price': 1726},
 {'seniority': 20,
  'home': 'owner',
  'time': 60,
  'age': 51,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 250.0,
  'assets': 2500.0,
  'debt': 0.0,
  'amount': 1250,
  'price': 1825},
 {'seniority': 0,
  'home': 'other',
  'time': 60,
  'age': 31,
  'marital': 'single',
  'records': 'no',
  'job': 'partime',
  'expenses': 35,
  'income': 128.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 900,
  'price': 982},
 {'seniority': 16,
  'home': 'parents',
  'time': 60,
  'age': 35,
  'marital': 'separated',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 105.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 800,
  'price': 1084},
 {'seniority': 4,
  'home': 'rent',
  'time': 60,
  'age': 33,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 82,
  'income': 69.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 2000,
  'price': 2216},
 {'seniority': 13,
  'home': 'private',
  'time': 48,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 81.0,
  'assets': 4750.0,
  'debt': 0.0,
  'amount': 1200,
  'price': 1385},
 {'seniority': 14,
  'home': 'owner',
  'time': 60,
  'age': 47,
  'marital': 'widow',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 35,
  'income': 100.0,
  'assets': 4000.0,
  'debt': 2000.0,
  'amount': 1475,
  'price': 1475},
 {'seniority': 7,
  'home': 'owner',
  'time': 60,
  'age': 55,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 124.0,
  'assets': 5000.0,
  'debt': 0.0,
  'amount': 800,
  'price': 982},
 {'seniority': 3,
  'home': 'owner',
  'time': 48,
  'age': 26,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 157.0,
  'assets': 7000.0,
  'debt': 0.0,
  'amount': 1200,
  'price': 2053},
 {'seniority': 3,
  'home': 'rent',
  'time': 48,
  'age': 39,
  'marital': 'married',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 97,
  'income': 223.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1250,
  'price': 1609},
 {'seniority': 20,
  'home': 'owner',
  'time': 36,
  'age': 40,
  'marital': 'single',
  'records': 'yes',
  'job': 'freelance',
  'expenses': 35,
  'income': 0.0,
  'assets': 8500.0,
  'debt': 400.0,
  'amount': 750,
  'price': 1100},
 {'seniority': 0,
  'home': 'owner',
  'time': 36,
  'age': 42,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 105,
  'income': 75.0,
  'assets': 10000.0,
  'debt': 0.0,
  'amount': 400,
  'price': 725},
 {'seniority': 23,
  'home': 'private',
  'time': 60,
  'age': 51,
  'marital': 'married',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 45,
  'income': 110.0,
  'assets': 2500.0,
  'debt': 0.0,
  'amount': 800,
  'price': 1343},
 {'seniority': 5,
  'home': 'rent',
  'time': 36,
  'age': 51,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 63,
  'income': 184.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 635,
  'price': 785},
 {'seniority': 6,
  'home': 'rent',
  'time': 60,
  'age': 34,
  'marital': 'separated',
  'records': 'no',
  'job': 'fixed',
  'expenses': 47,
  'income': 120.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1100,
  'price': 1700},
 {'seniority': 12,
  'home': 'owner',
  'time': 24,
  'age': 38,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 114.0,
  'assets': 4000.0,
  'debt': 600.0,
  'amount': 400,
  'price': 1169},
 {'seniority': 0,
  'home': 'owner',
  'time': 60,
  'age': 24,
  'marital': 'married',
  'records': 'no',
  'job': 'others',
  'expenses': 35,
  'income': 104.0,
  'assets': 7000.0,
  'debt': 2500.0,
  'amount': 1350,
  'price': 1425},
 {'seniority': 10,
  'home': 'private',
  'time': 48,
  'age': 28,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 129.0,
  'assets': 3500.0,
  'debt': 933.0,
  'amount': 1000,
  'price': 1529},
 {'seniority': 3,
  'home': 'parents',
  'time': 48,
  'age': 24,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 55.0,
  'assets': 3000.0,
  'debt': 0.0,
  'amount': 850,
  'price': 875},
 {'seniority': 3,
  'home': 'private',
  'time': 6,
  'age': 24,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 173.0,
  'assets': 4800.0,
  'debt': 0.0,
  'amount': 475,
  'price': 1323},
 {'seniority': 10,
  'home': 'rent',
  'time': 60,
  'age': 38,
  'marital': 'married',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 110,
  'income': 204.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1500,
  'price': 1531},
 {'seniority': 8,
  'home': 'other',
  'time': 24,
  'age': 33,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 166.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1150,
  'price': 1770},
 {'seniority': 1,
  'home': 'rent',
  'time': 60,
  'age': 40,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 57,
  'income': 120.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1500,
  'price': 1737},
 {'seniority': 2,
  'home': 'owner',
  'time': 60,
  'age': 27,
  'marital': 'single',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 35,
  'income': 120.0,
  'assets': 8000.0,
  'debt': 0.0,
  'amount': 975,
  'price': 1140},
 {'seniority': 1,
  'home': 'parents',
  'time': 60,
  'age': 30,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 113.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 930,
  'price': 955},
 {'seniority': 0,
  'home': 'other',
  'time': 36,
  'age': 41,
  'marital': 'married',
  'records': 'yes',
  'job': 'freelance',
  'expenses': 35,
  'income': 0.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 1600},
 {'seniority': 10,
  'home': 'rent',
  'time': 24,
  'age': 39,
  'marital': 'single',
  'records': 'yes',
  'job': 'others',
  'expenses': 55,
  'income': 195.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 400,
  'price': 435},
 {'seniority': 2,
  'home': 'owner',
  'time': 60,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 190.0,
  'assets': 4500.0,
  'debt': 1200.0,
  'amount': 1575,
  'price': 1611},
 {'seniority': 6,
  'home': 'owner',
  'time': 48,
  'age': 24,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 227.0,
  'assets': 3000.0,
  'debt': 0.0,
  'amount': 600,
  'price': 1380},
 {'seniority': 0,
  'home': 'rent',
  'time': 60,
  'age': 21,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 35,
  'income': 0.0,
  'assets': 16000.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 1000},
 {'seniority': 20,
  'home': 'parents',
  'time': 36,
  'age': 38,
  'marital': 'married',
  'records': 'yes',
  'job': 'freelance',
  'expenses': 60,
  'income': 0.0,
  'assets': 25000.0,
  'debt': 0.0,

In [28]:
train_dicts = df_train.to_dict(orient = "records")

In [29]:
dv = DictVectorizer(sparse = False)
X_train = dv.fit_transform(train_dicts)

In [30]:
dv.get_feature_names_out()

array(['age', 'amount', 'assets', 'debt', 'expenses', 'home=ignore',
       'home=other', 'home=owner', 'home=parents', 'home=private',
       'home=rent', 'home=unk', 'income', 'job=fixed', 'job=freelance',
       'job=others', 'job=partime', 'job=unk', 'marital=divorced',
       'marital=married', 'marital=separated', 'marital=single',
       'marital=unk', 'marital=widow', 'price', 'records=no',
       'records=yes', 'seniority', 'time'], dtype=object)

In [31]:
df_train.isna().sum()

seniority    0
home         0
time         0
age          0
marital      0
records      0
job          0
expenses     0
income       0
assets       0
debt         0
amount       0
price        0
dtype: int64

In [32]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [33]:
df_val = df_val.fillna(0)

In [34]:
val_dicts = df_val.to_dict(orient = 'records')

In [35]:
X_val = dv.transform(val_dicts)

In [36]:
y_pred= dt.predict_proba(X_val)[:,1]

In [37]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1.,
       0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0.])

In [38]:
roc_auc_score(y_val, y_pred)

0.6551488217771427

Lets check on training dataset

In [39]:
y_pred= dt.predict_proba(X_train)[:,1]

In [40]:
roc_auc_score(y_train, y_pred)

1.0

On training data, AUC is 1, but on validation data its .64. This is called overfitting

We will control depth of the tree using (max_depth = 4)

In [41]:
dt = DecisionTreeClassifier(max_depth = 4)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4)

In [42]:
y_pred= dt.predict_proba(X_train)[:,1]
auc = roc_auc_score(y_train, y_pred)
print('train:', auc)

y_pred= dt.predict_proba(X_val)[:,1]
auc = roc_auc_score(y_val, y_pred)
print('val:', auc)

train: 0.8164293560926146
val: 0.7612827250490422

In [43]:
from sklearn.tree import export_text

In [44]:
print(export_text(dt, feature_names = dv.get_feature_names_out()))

|--- records=no <= 0.50
|   |--- seniority <= 6.50
|   |   |--- amount <= 862.50
|   |   |   |--- seniority <= 0.50
|   |   |   |   |--- class: 1
|   |   |   |--- seniority >  0.50
|   |   |   |   |--- class: 0
|   |   |--- amount >  862.50
|   |   |   |--- assets <= 8250.00
|   |   |   |   |--- class: 1
|   |   |   |--- assets >  8250.00
|   |   |   |   |--- class: 0
|   |--- seniority >  6.50
|   |   |--- income <= 103.50
|   |   |   |--- assets <= 4500.00
|   |   |   |   |--- class: 1
|   |   |   |--- assets >  4500.00
|   |   |   |   |--- class: 0
|   |   |--- income >  103.50
|   |   |   |--- expenses <= 89.00
|   |   |   |   |--- class: 0
|   |   |   |--- expenses >  89.00
|   |   |   |   |--- class: 1
|--- records=no >  0.50
|   |--- job=partime <= 0.50
|   |   |--- income <= 74.50
|   |   |   |--- assets <= 4250.00
|   |   |   |   |--- class: 0
|   |   |   |--- assets >  4250.00
|   |   |   |   |--- class: 0
|   |   |--- income >  74.50
|   |   |   |--- seniority <= 5.50
|   |   |   |   |--- class: 0
|   |   |   |--- seniority >  5.50
|   |   |   |   |--- class: 0
|   |--- job=partime >  0.50
|   |   |--- assets <= 8750.00
|   |   |   |--- time <= 27.00
|   |   |   |   |--- class: 0
|   |   |   |--- time >  27.00
|   |   |   |   |--- class: 1
|   |   |--- assets >  8750.00
|   |   |   |--- class: 0

In [45]:
df

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129.0,0.0,0.0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131.0,0.0,0.0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200.0,3000.0,0.0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182.0,2500.0,0.0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107.0,0.0,0.0,310,910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4449,default,1,rent,60,39,married,no,fixed,69,92.0,0.0,0.0,900,1020
4450,ok,22,owner,60,46,married,no,fixed,60,75.0,3000.0,600.0,950,1263
4451,default,0,owner,24,37,married,no,partime,60,90.0,3500.0,0.0,500,963
4452,ok,0,rent,48,23,single,no,freelance,49,140.0,0.0,0.0,550,550
4453,ok,5,owner,60,32,married,no,freelance,60,140.0,4000.0,1000.0,1350,1650

# 6.5 Decision Tree Parameter tuning

- Selecting max_depth  
- Selecting min_samples_leaf

Tree has multiple parameters, two impoertant ones are:  
- Max-depth
- how we decide if a leave is sufficently large and not pure. It is the minimum number of samples that must exist in a leaf node after a split.

In [ ]:
DecisionTreeClassifier